services:
  - type: worker
    name: telegram-card-sender
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: DB_ENCRYPTION_KEY
        sync: false
        generateValue: true
    autoDeploy: true
